code --install-extension akamud.vscode-theme-onedark
code --install-extension bierner.markdown-preview-github-styles
code --install-extension icrawl.discord-vscode
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension PKief.material-icon-theme
code --install-extension vscodevim.vim
